<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20180906151036 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('CREATE TABLE internezzo_formdata_domain_model_collector (persistence_object_identifier VARCHAR(40) NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE internezzo_formdata_domain_model_formdata (persistence_object_identifier VARCHAR(40) NOT NULL, collector VARCHAR(40) DEFAULT NULL, payload LONGTEXT NOT NULL COMMENT \'(DC2Type:flow_json_array)\', receiveddatetime DATETIME DEFAULT NULL, INDEX IDX_5250A6B8CEDBF54C (collector), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE internezzo_formdata_domain_model_formdata ADD CONSTRAINT FK_5250A6B8CEDBF54C FOREIGN KEY (collector) REFERENCES internezzo_formdata_domain_model_collector (persistence_object_identifier)');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE internezzo_formdata_domain_model_formdata DROP FOREIGN KEY FK_5250A6B8CEDBF54C');
        $this->addSql('DROP TABLE internezzo_formdata_domain_model_collector');
        $this->addSql('DROP TABLE internezzo_formdata_domain_model_formdata');
        $this->addSql('ALTER TABLE neos_contentrepository_domain_model_nodedata DROP INDEX UNIQ_CE6515692D45FE4D, ADD INDEX IDX_CE6515692D45FE4D (movedto)');
        $this->addSql('ALTER TABLE neos_flow_resourcemanagement_persistentresource RENAME INDEX idx_6954b1f63332102a TO IDX_35DC14F03332102A');
        $this->addSql('ALTER TABLE neos_googleanalytics_domain_model_siteconfiguration RENAME INDEX idx_dacc5fd9694309e4 TO IDX_D675F674694309E4');
        $this->addSql('CREATE INDEX sourceuripathhash ON neos_redirecthandler_databasestorage_domain_model_redirect (sourceuripathhash, host)');
    }
}